#!/usr/bin/ruby

require "selenium-webdriver"

if !Process.uid.zero?
	puts "Run it as a root user: sudo #{__FILE__}"
	exit 130
end 

`systemctl start tor` # start the tor service

options = Selenium::WebDriver::Options.chrome(detach: true, "args" => ["proxy-server=socks5://127.0.0.1:9050"])

driver = Selenium::WebDriver.for(:chrome,:options => options)
driver.navigate.to "https://google.com"

trap "SIGINT" do
  puts "\nTerminating"
  driver.quit if driver
  `systemctl stop tor`
  exit 130
end

sleep # prevent the script to terminate

# TODO 
# we need to check if the browser window is closed in order to terminate the script


